// ============================================================================
// NIGHTWATCH GEM — full mount assembly
// Composes the parametric parts into a German Equatorial Mount on its pier,
// posed in the classic "counterweight-down / OTA-to-pole" park.
// Parametric OpenSCAD model.  Units: MILLIMETRES.
//
// Render (OpenSCAD not installed here):
//     openscad -o assembly.stl                     assembly.scad
//     openscad -o assembly.png --imgsize=1600,1200 assembly.scad
//
// The immediate, dependency-free visual is design/mechanical/cad/preview_assembly.svg
// (generated by svg_preview.py, which reads the SAME params.py numbers).
//
// Dimensions trace to design/mechanical/calc/params.py (SI metres -> mm).
// ============================================================================

use <ra_housing.scad>
use <dec_housing.scad>
use <pier_adapter.scad>
use <counterweight_shaft.scad>

$fn = 64;

// ---- parameters (traced to params.py) --------------------------------------
lat        = 38.9;     // P.SITE.latitude_deg  -> polar-axis altitude
pier_h     = 914.4;    // P.PIER.height_above_m = u.inch(36)
pier_d     = 304.8;    // P.PIER.diameter_m     = u.inch(12)
tp_side    = 304.8;    // P.PIER.top_plate_side_m = u.inch(12)
tp_thk     = 9.525;    // P.PIER.top_plate_thk_m  = u.inch(0.375)
adapter_thk = 19.05;   // pier_adapter.scad (0.75 in), ASSUMED added part

ra_depth   = 76.2;     // P.RA_HOUSING.depth_m  = u.inch(3)
dec_face   = 152.4;    // P.DEC_HOUSING.outer_x_m = u.inch(6)
dec_depth  = 63.5;     // P.DEC_HOUSING.depth_m  = u.inch(2.5)

// Default OTA = MN78 (the params default across the torque/balance/pier proofs).
ota_od     = 210.0;    // P.MN78.tube_od_m      = u.mm(210)
ota_len    = 1400.0;   // P.MN78.tube_length_m  = u.mm(1400)
saddle_stack = 50.0;   // stiffness.SADDLE_LEVER_M (assumed saddle offset)

// Derived placements
adapter_top = pier_h + tp_thk + adapter_thk;
L_ra = ra_depth + dec_face/2 + 40;     // DEC-head seat along the polar axis (DERIVED)
ota_offset = dec_face/2 + saddle_stack + ota_od/2;   // saddle-side radial offset

// ---- assembly --------------------------------------------------------------
module gem_assembly() {
    // Concrete pier (exposed height only)
    color([0.62, 0.62, 0.60]) cylinder(d = pier_d, h = pier_h);

    // Steel top plate (SOURCED, P.PIER)
    color([0.30, 0.30, 0.32])
        translate([-tp_side/2, -tp_side/2, pier_h]) cube([tp_side, tp_side, tp_thk]);

    // Pier adapter plate (10x10x0.75 in, ASSUMED added part)
    color([0.80, 0.67, 0.24])
        translate([0, 0, pier_h + tp_thk]) pier_adapter();

    // ---- mount head, mounted on the polar (RA) axis ----
    translate([0, 0, adapter_top])
        rotate([0, 90 - lat, 0]) {          // local +z -> celestial pole (alt = lat)

            color([0.75, 0.78, 0.80]) ra_housing();

            // DEC head at the far end of the RA axis; DEC axis _|_ RA axis
            translate([0, 0, L_ra]) {

                rotate([90, 0, 0]) color([0.70, 0.73, 0.76]) dec_housing();

                // Counterweight shaft on the "down" side (classical GEM option;
                // balance.py recommends deleting it — drawn for completeness).
                translate([0, dec_face/2, 0])
                    rotate([-90, 0, 0]) color([0.20, 0.20, 0.22]) counterweight_shaft();

                // OTA tube, parallel to the polar axis, on the saddle side.
                // Saddle sits ~1/3 up the tube (matches OTA.cg_from_saddle model).
                translate([0, -ota_offset, -ota_len/3])
                    color([0.10, 0.10, 0.12]) cylinder(d = ota_od, h = ota_len);
            }
        }
}

gem_assembly();
